### ISSUE TITLE
Trouble running

### ISSUE THREAD

**Issue by t3mp0r4ry23** [stillmotion/terminal-games#4]
Hello!

I can’t seem to figure out how to run any of the games. Could someone help me out?

Thanks!

**Comment by mexchip** [comment]
If you're running Ubuntu (or any Debian based Linux distribution), run the following commands on a terminal:

Install compiler and standard libraries:
`$ sudo apt install build-essential`

Install termbox dependency:
`$ sudo apt install libtermbox-dev`

Clone the terminal-games repository and compile the games:
```
$ git clone https://github.com/stillmotion/terminal-games.git
$ cd terminal-games
$ make
cc     invaders.c  -s -ltermbox -o invaders
cc     minesweeper.c  -s -ltermbox -o minesweeper
cc     snake.c  -s -ltermbox -o snake
cc     sokoban.c  -s -ltermbox -o sokoban
cc     sudoku.c  -s -ltermbox -o sudoku
cc     tetris.c  -s -ltermbox -o tetris

```
Now you can run the games:
```
$ ./invaders
$ ./minesweeper
...
```

**Comment by t3mp0r4ry23** [comment]
Thank you!
